modules: inherit :dev profile
when running `lein repl` from the muuntaja module there was the
following error

```sh
Error: Could not find or load main class clojure.main
Caused by: java.lang.ClassNotFoundException: clojure.main
Subprocess failed (exit code: 1)
```

This error means that the Clojure jar was not in the
classpath. Inheriting the :dev profile fixes that issue.